## Задание 1

Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:

- оценка **2 и ниже** — низкий рейтинг;
- оценка **4 и ниже** — средний рейтинг;
- оценка **4.5 и 5** — высокий рейтинг.

Результат классификации запишите в столбец `class`.

In [4]:
import pandas as pd

In [5]:
df_movies = pd.read_csv('movies.csv')
df_ratings = pd.read_csv('ratings.csv')

In [17]:
df_movies['movieId'].unique()

array([     1,      2,      3, ..., 163949, 164977, 164979], shape=(9125,))

In [10]:
df_rated = df_ratings.groupby('movieId').mean()['rating']

In [24]:
df_rated

movieId
1         3.872470
2         3.401869
3         3.161017
4         2.384615
5         3.267857
            ...
161944    5.000000
162376    4.500000
162542    5.000000
162672    3.000000
163949    5.000000
Name: rating, Length: 9066, dtype: float64

In [29]:
def rating(rating):
    if rating <= 2:
        return 'Low rating'
    if rating <= 4:
        return 'Medium rating'
    return 'High rating'

In [30]:
df_movies['class'] = df_rated.apply(rating)
df_movies['class'] = df_movies['class'].fillna('no_rating')

In [31]:
df_movies

,movieId,title,genres,class
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,no_rating
1,2,Jumanji (1995),Adventure|Children|Fantasy,Medium rating
2,3,Grumpier Old Men (1995),Comedy|Romance,Medium rating
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,Medium rating
4,5,Father of the Bride Part II (1995),Comedy,Medium rating
...,...,...,...,...
9120,162672,Mohenjo Daro (2016),Adventure|Drama|Romance,no_rating
9121,163056,Shin Godzilla (2016),Action|Adventure|Fantasy|Sci-Fi,no_rating
9122,163949,The Beatles: Eight Days a Week - The Touring Y...,Documentary,no_rating
9123,164977,The Gay Desperado (1936),Comedy,no_rating
9124,164979,"Women of '69, Unboxed",Documentary,no_rating

## Задание 2

Используйте файл `keywords.csv`.

Нужно написать **гео-классификатор**, который для каждой строки (поискового запроса) определяет географическую принадлежность к одному из регионов. Если поисковый запрос содержит название города региона, то в столбце `region` нужно записать название этого региона. Если поисковый запрос не содержит ни одного города из словаря, то в `region` ставим значение `undefined`.

Правила распределения по регионам:

```python
geo_data = {
    'Центр': ['москва', 'тула', 'ярославль'],
    'Северо-Запад': ['петербург', 'псков', 'мурманск'],
    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}
```

Результат классификации запишите в отдельный столбец `region`.

geo_data = {
    'Центр': ['москва', 'тула', 'ярославль'],
    'Северо-Запад': ['петербург', 'псков', 'мурманск'],
    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

In [44]:
def region(string):
    words = string.lower()
    for reg, cities in geo_data.items():
        for city in cities:
            if city in words:
                return reg
    return 'undefined'

In [46]:
df_keywords = pd.read_csv('keywords.csv')
df_keywords['region'] = df_keywords['keyword'].apply(region)

In [48]:
df_keywords[df_keywords.region != 'undefined']

                                     keyword   shows          region
127                             авито москва  979292           Центр
370                 авито ру санкт петербург  425134    Северо-Запад
564                погода в санкт петербурге  292489    Северо-Запад
849                          авито ярославль  209581           Центр
1063                     фарпост владивосток  176951  Дальний Восток
...                                      ...     ...             ...
99590  авито ярославль автомобили с пробегом    3673           Центр
99634   северпост новости мурманской области    3606    Северо-Запад
99808      полармед мурманск запись на прием    3719    Северо-Запад
99890                    яндекс метро москва    4548           Центр
99922                      авто ру ярославль    3712           Центр

[747 rows x 3 columns]

### Задание 3

Есть мнение, что раньше снимали настоящее кино, не то что сейчас. Ваша задача — проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия: файл `movies.csv` и `ratings.csv` из базы. Нужно проверить, верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

Вы не будете затрагивать субъективные факторы выставления этих рейтингов, а пройдётесь по алгоритму:

1. В переменную `years` запишите список из всех годов с 1950 по 2010 года.
2. Напишите функцию `production_year`, которая каждой строке из названия фильма выставляет год выпуска. Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте алгоритм:
    * Для каждой строки пройдите по всем годам списка `years`;
    * Если номер года присутствует в названии фильма, то функция возвращает этот год, как год выпуска;
    * Если ни один из номеров года списка `years` не встретился в названии фильма, то возвращается 1900 год.
3. Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец `year`.
4. Посчитайте средний рейтинг всех фильмов для каждого значения столбца `year` и отсортируйте результат по убыванию рейтинга.

In [2]:
years = list(range(1950, 2011))

In [7]:
def production_year(title):
    for year in years:
        if str(year) in title:
            return year
    return 1900

In [8]:
df_movies['year'] = df_movies['title'].apply(production_year)

In [13]:
df_movies['rating'] = df_rated

In [17]:
df_by_year = df_movies.groupby('year')['rating'].mean().reset_index()
df_by_year.sort_values(by='rating', ascending=False)

    year    rating
61  2010  3.573369
48  1997  3.569454
25  1974  3.567137
12  1961  3.488254
2   1951  3.484776
..   ...       ...
30  1979  3.127991
15  1964  3.107498
8   1957  3.072417
28  1977  3.071953
16  1965  2.926170

[62 rows x 2 columns]