In [2]:
import pandas as pd

# Задание 1

Датасет для домашнего задания находится в материалах занятия — файлы для домашнего задания «Библиотека Pandas».

**Определите, какому фильму было выставлено больше всего оценок 5.0.**

In [10]:
movies_data = pd.read_csv('Data 1/movies.csv')
ratings_data = pd.read_csv('Data 1/ratings.csv')

In [9]:
movies_data.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [11]:
ratings_data.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [27]:
df_joined = movies_data.merge(ratings_data, on='movieId', how='inner')
df_5 = df_joined[df_joined['rating'] == 5.0]
best_movieId = df_5.groupby('movieId').size().max()
print (movies_data[movies_data['movieId'] == best_movieId]['title'])

126    Batman Forever (1995)
Name: title, dtype: str

# Задание 2

По данным файла `power.csv` посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 год.  
Не учитывайте в расчётах отрицательные значения `quantity`.

In [28]:
power_data = pd.read_csv('Data 2/power.csv')

In [37]:
df_baltic = power_data[power_data['country'].isin(['Latvia', 'Lithuania', 'Estonia'])]
df_baltic = df_baltic[df_baltic['category'].isin([4,12,21])]
df_baltic = df_baltic[(df_baltic['year'] >= 2005) & (df_baltic['year'] <= 2010)]
df_baltic = df_baltic[df_baltic['quantity'] >= 0]
print(df_baltic['quantity'].sum())

240580.0

# Задание 3

Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в `pandas DataFrame`. Вы можете взять любые страницы.  

Примеры страниц:  
- [https://fortrader.org/quotes](https://fortrader.org/quotes)  
- [https://pythonworld.ru/tipy-dannyx-v-python/stroki-funkcii-i-metody-strok.html](https://pythonworld.ru/tipy-dannyx-v-python/stroki-funkcii-i-metody-strok.html)

In [6]:
page_url = 'https://iss.moex.com/iss/history/engines/stock/markets/shares/boards/TQBR/securities/SBER/securities.html'
df = pd.read_html(page_url, encoding='utf-8')

In [9]:
df[0]

,BOARDID (string:12),TRADEDATE (date:10),SHORTNAME (string:189),SECID (string:36),NUMTRADES (double),VALUE (double),OPEN (double),LOW (double),HIGH (double),LEGALCLOSEPRICE (double),...,MARKETPRICE3 (double),ADMITTEDQUOTE (double),MP2VALTRD (double),MARKETPRICE3TRADESVALUE (double),ADMITTEDVALUE (double),WAVAL (double),TRADINGSESSION (int32),CURRENCYID (string:9),TRENDCLSPR (double),TRADE_SESSION_DATE (date:10)
0,TQBR,2013-03-25,Сбербанк,SBER,140,59340002.8,96.00,96.00,101.14,98.66,...,99.99,99.99,8.572434e+09,8.572434e+09,8.572434e+09,NaN,3,SUR,NaN,NaN
1,TQBR,2013-03-26,Сбербанк,SBER,183,126030358.8,98.58,97.08,99.31,97.13,...,97.82,97.82,1.221847e+10,1.221847e+10,1.221847e+10,NaN,3,SUR,-1.61,NaN
2,TQBR,2013-03-27,Сбербанк,SBER,176,121835900.2,97.90,95.39,98.00,96.73,...,96.45,96.45,1.251981e+10,1.251981e+10,1.251981e+10,NaN,3,SUR,-0.46,NaN
3,TQBR,2013-03-28,Сбербанк,SBER,299,192469794.9,96.38,95.72,98.66,98.64,...,97.74,97.74,1.257281e+10,1.257281e+10,1.257281e+10,NaN,3,SUR,1.90,NaN
4,TQBR,2013-03-29,Сбербанк,SBER,121,77268860.1,98.60,98.32,99.09,98.83,...,98.77,98.77,2.611474e+09,2.611474e+09,2.611474e+09,NaN,3,SUR,0.17,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,TQBR,2013-08-08,Сбербанк,SBER,2401,890408055.5,95.00,93.32,95.15,94.00,...,94.15,94.15,5.923967e+09,5.923967e+09,5.923967e+09,NaN,3,SUR,-0.41,NaN
96,TQBR,2013-08-09,Сбербанк,SBER,2514,860309410.9,94.48,93.95,95.74,95.66,...,94.86,94.86,6.528187e+09,6.528187e+09,6.528187e+09,NaN,3,SUR,1.71,NaN
97,TQBR,2013-08-12,Сбербанк,SBER,2451,816471222.0,95.80,94.78,96.40,96.21,...,95.48,95.48,5.652812e+09,5.652812e+09,5.652812e+09,NaN,3,SUR,0.54,NaN
98,TQBR,2013-08-13,Сбербанк,SBER,2194,917885512.5,95.93,95.93,97.93,97.20,...,97.34,97.34,7.378259e+09,7.378259e+09,7.378259e+09,NaN,3,SUR,1.23,NaN
99,TQBR,2013-08-14,Сбербанк,SBER,2041,982308738.2,97.65,97.22,98.24,97.98,...,97.78,97.78,6.398053e+09,6.398053e+09,6.398053e+09,NaN,3,SUR,0.69,NaN