In [2]:
import pandas as pd

# Задание 1

Датасет для домашнего задания находится в материалах занятия — файлы для домашнего задания «Библиотека Pandas».

**Определите, какому фильму было выставлено больше всего оценок 5.0.**

In [10]:
movies_data = pd.read_csv('Data 1/movies.csv')
ratings_data = pd.read_csv('Data 1/ratings.csv')

In [9]:
movies_data.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [11]:
ratings_data.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [27]:
df_joined = movies_data.merge(ratings_data, on='movieId', how='inner')
df_5 = df_joined[df_joined['rating'] == 5.0]
best_movieId = df_5.groupby('movieId').size().max()
print (movies_data[movies_data['movieId'] == best_movieId]['title'])

126    Batman Forever (1995)
Name: title, dtype: str

# Задание 2

По данным файла `power.csv` посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 год.  
Не учитывайте в расчётах отрицательные значения `quantity`.

In [28]:
power_data = pd.read_csv('Data 2/power.csv')

In [37]:
df_baltic = power_data[power_data['country'].isin(['Latvia', 'Lithuania', 'Estonia'])]
df_baltic = df_baltic[df_baltic['category'].isin([4,12,21])]
df_baltic = df_baltic[(df_baltic['year'] >= 2005) & (df_baltic['year'] <= 2010)]
df_baltic = df_baltic[df_baltic['quantity'] >= 0]
print(df_baltic['quantity'].sum())

240580.0

# Задание 3

Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в `pandas DataFrame`. Вы можете взять любые страницы.  

Примеры страниц:  
- [https://fortrader.org/quotes](https://fortrader.org/quotes)  
- [https://pythonworld.ru/tipy-dannyx-v-python/stroki-funkcii-i-metody-strok.html](https://pythonworld.ru/tipy-dannyx-v-python/stroki-funkcii-i-metody-strok.html)

In [5]:
page_url = 'https://fortrader.org/quotes'
df = pd.read_html(page_url, encoding='utf-8')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 1: invalid start byte